const data = [
    {
      userId: "1",
      title: "Atomic Habits",
      description: "A book about building good habits and breaking bad ones.",
      image: ["https://images-na.ssl-images-amazon.com/images/I/91bYsX41DVL.jpg"],
      favorite: true,
      audioLength: "5:30",
      timestamp: "Jan 31, 2025 · 5:26 PM",
      type: "audio",
    },
    {
      userId: "2",
      title: "Deep Work",
      description: "A guide to focusing without distractions in a noisy world.",
      image: ["https://images-na.ssl-images-amazon.com/images/I/81j3r9ZGnHL.jpg"],
      favorite: false,
      audioLength: "4:45",
      timestamp: "Feb 30, 2025 · 5:26 PM",
      type: "text",
    },
    {
      userId: "3",
      title: "Can't Hurt Me",
      description: "David Goggins shares his story of mental toughness.",
      image: ["https://images-na.ssl-images-amazon.com/images/I/91N7FM2Bs7L.jpg"],
      favorite: true,
      audioLength: "6:10",
      timestamp: "Mar 3, 2025 · 5:26 PM",
      type: "audio",
    },
    {
      userId: "4",
      title: "The Power of Now",
      description: "A book about living in the present moment.",
      image: ["https://images-na.ssl-images-amazon.com/images/I/71mP1LhSxLL.jpg"],
      favorite: false,
      audioLength: "3:25",
      timestamp: "Dec 30, 2025 · 5:26 PM",
      type: "text",
    },
    {
      userId: "5",
      title: "The Subtle Art of Not Giving a F*ck",
      description: "A counterintuitive approach to living a good life.",
      image: ["https://images-na.ssl-images-amazon.com/images/I/81tW5OpHNVL.jpg"],
      favorite: true,
      audioLength: "5:00",
      timestamp: "Oct 30, 2025 · 5:26 PM",
      type: "audio",
    },
    {
      userId: "6",
      title: "The Alchemist",
      description: "A novel about finding one's destiny.",
      image: ["https://images-na.ssl-images-amazon.com/images/I/71aFt4+OTOL.jpg"],
      favorite: false,
      audioLength: "4:20",
      timestamp: "Nov 30, 2025 · 5:26 PM",
      type: "text",
    },
    {
      userId: "7",
      title: "Rich Dad Poor Dad",
      description: "Financial lessons from two father figures.",
      image: ["https://images-na.ssl-images-amazon.com/images/I/81bsw6fnUiL.jpg"],
      favorite: true,
      audioLength: "6:15",
      timestamp: "Dec 30, 2025 · 5:26 PM",
      type: "audio",
    },
    {
      userId: "8",
      title: "Think and Grow Rich",
      description: "A classic book on success and mindset.",
      image: ["https://images-na.ssl-images-amazon.com/images/I/81zq5h12fqL.jpg"],
      favorite: false,
      audioLength: "7:00",
      timestamp: "Apr 30, 2025 · 5:26 PM",
      type: "text",
    },
    {
      userId: "9",
      title: "The 4-Hour Workweek",
      description: "A book about escaping the 9-5 grind and living life on your own terms.",
      image: ["https://images-na.ssl-images-amazon.com/images/I/71pFe69ZPvL.jpg"],
      favorite: true,
      audioLength: "5:50",
      timestamp: "May 30, 2025 · 5:26 PM",
      type: "audio",
    },
    {
      userId: "10",
      title: "Start With Why",
      description: "Understanding the importance of 'Why' in leadership and life.",
      image: ["https://images-na.ssl-images-amazon.com/images/I/71T0b3HbM1L.jpg"],
      favorite: false,
      audioLength: "4:10",
      timestamp: "Jun 30, 2025 · 5:26 PM",
      type: "text",
    },
  ];
  
  export default data;
  